public class ExceptionHandlingDemo {
    public static void main(String[] args) {
        try {
            
            int[] numbers = {1, 2, 3};
            System.out.println("Accessing the fourth element: " + numbers[3]);
        } catch (ArrayIndexOutOfBoundsException e) {

            System.out.println("Exception caught: Array index is out of bounds!");
        } finally {
            
            System.out.println("The 'finally' block is always executed.");
        }
        System.out.println("Program execution continues...");
    }
}
